[package]
name = "my_simple_project"
version = "0.1.0"
authors = ["xGabrielDEV <58668092+xGabrielDEV@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
